RAC-103 feat: 대학원생 멘토링 관련
WE-ARE-RACCOONS/postgraduate-back pull request #30
Opened 2023-11-06 09:35 UTC by ay-eonii

## 🦝 PR 요약
대학원생 멘토링 관련한 기능을 추가했습니다.

## ✨ PR 상세 내용
+ 내 멘토링 목록 조회(확정 대기, 진행 예정, 완료)
+ 내 멘토링 상세 조회(멘토링 요청서 조회)
+ 내 멘토링 시간 변경
+ 내 멘토링 상태 변경
+ 내 멘토링 거절 사유 변경

## 🚨 주의 사항

## ✅ 체크 리스트

- [x] 리뷰어 설정했나요?
- [x] Label 설정했나요?
- [x] 제목 양식 맞췄나요? (ex. RAC-1 feat: 기능 추가)
- [x] 변경 사항에 대한 테스트 진행했나요?

2023-11-07 08:29 UTC, ywj9811 requested changes
대학원생 상태 변경 / 거절 사유 변경에 관련해서 논의할 점이 있을 듯 해요
- 대학원생 상태 변경 -> 여기에서 거절, 진행예정 이렇게 변경하고
- 거절 사유 변경 -> 여기서 거절 사유를 선택
이렇게 하는 것 같은데, 거절을 선택하면 동시에 거절 사유 선택을 하기 때문에 이 둘이 따로 있으면 불필요한 통신이 될 듯 해요

명세서를 보면 아래와 같은데
- 멘토링 거절: [멘토링 거절] 버튼을 누르면 거절 사유를 묻는 모달창 나옴. '요청 시간에 일정이 있음', '사전 질문이 연구 분야와 다름' + 기타사유 입력창(줄글 텍스트) 세 가지 선택지의 체크박스. x 누르면 <진행예정>탭으로 이동.
사유 선택을 완료해야 거절 + 사유가 들어가고 x를 누르면 진행 예정으로 이동되는 것 같은데, 그렇다면 거절과 사유는 같이 들어와야 하지 않을까요?

그렇다면 API를 분리하는 것은 어떨까요?
한개는 진행 예정으로 변경하는 API
한개는 거절, 거절 사유를 동시에 업데이트 하는 API
이렇게 한다면 어떨까요?

분리를 하게 된다면 대학생의 경우에도 분리를 할지 고민을 해보죠

2023-11-07 08:29 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringUpdateService.java
> +    public void updateStatus(Mentoring mentoring, String refuse) {
updateStatus() 함수 이름이랑 내용이 안맞는 것 같아요
Status에 대한 변경은 안들어가있어서 어색한 것 같아요

2023-11-07 08:29 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
> +    public ResponseDto getSeniorMentorings(@AuthenticationPrincipal AuthDetails authDetails,
getSeniorMentoring 보다 더 알맞는 이름이 있지 않을까요?

2023-11-07 10:13 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringUpdateService.java
> +    public void updateStatus(Mentoring mentoring, String refuse) {
앗 감사합니다! 수정하겠습니다

2023-11-07 10:14 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
> +    public ResponseDto getSeniorMentorings(@AuthenticationPrincipal AuthDetails authDetails,
넵 생각해보고 수정하겠습니다!

2023-11-09 04:02 UTC, ywj9811 requested changes

2023-11-09 04:02 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/mentoring/application/dto/req/MentoringStatusRequest.java
단순한 문제이지만 MentoringStatusRequest보다는 MentoringRefuseRequest가 낫지 않을까요?

2023-11-09 04:05 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseCode.java
멘토링 예외 코드는 700번대 시작 아닌가요?
EX700
EX701
EX702
괜찬ㄴㅎ을까요

2023-11-09 04:08 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseCode.java
앗 수정하겠습니다!!

2023-11-09 04:12 UTC, merged