RAC-186: 관리자 관련
WE-ARE-RACCOONS/postgraduate-back pull request #62
Opened 2023-12-05 13:47 UTC by ay-eonii

## 🦝 PR 요약
+ 관리자 관련 기능을 구현했습니다.

## ✨ PR 상세 내용
+ 후배 목록 조회
+ 후배 매칭지원 정보 상세 조회
+ 후배 멘토링 정보
<br>

+ 선배 목록 조회
+ 선배 인증 조회
+ 선배 승인 상태 변경
+ 선배 멘토링 정보
+ 선배 정산 정보
<br>

+ 정산 목록
 + 매달 기준이라고 하여 `salaryDate` 로 가져옵니다.
<br>

+ 결제 목록
+ 멘토링별 결제정보 상세 조회

## 🚨 주의 사항
+ 정산 상태를 `Boolean` 으로 저장하고 있는데, 관리자에서 `O`(DONE), `X`(YET), `-`(NONE) 3가지가 필요하여 dto 에서 enum으로 관리했습니다.
+ [매칭 지원 완료 여부] 는 아직 명확히 기능을 이해하지 못해 추후에 추가하겠습니다.

## ✅ 체크 리스트

- [X] 리뷰어 설정했나요?
- [x] Label 설정했나요?
- [x] 제목 양식 맞췄나요? (ex. RAC-1 feat: 기능 추가)
- [x] 변경 사항에 대한 테스트 진행했나요?

2023-12-06 16:44 UTC, ywj9811 requested changes
전체적으로 자주 언급된 내용은
수정되는 dto 모두 record로 변경해주세요!
List<dto> 형식으로 반환되는 내용이 많은데, 기존에 사용하던 방식이 Dto가 List<>를 감싸는 방식이었다보니 고민을 해볼 필요가 있을 것 같아요!

그외에 몇가지 내용이 있습니다!

2023-12-06 16:44 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/admin/application/usecase/UserManageByAdminUseCase.java
> +    public List<UserResponse> getUsers() {
이부분도 반환형 어떻게 할지..!
그리고 findAll() 호출하는 getService의 메소드명이 어디서는 getAll()이고 여기는 all()인데 무엇이 좋을까요?
나중에라도 정리해서 통일하면 좋을 것 같아요

2023-12-06 16:44 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/admin/presentation/AdminController.java
>      @Operation(summary = "[관리자] 선배 프로필 승인 요청 응답", description = "선배 승인 신청한 유저를 승인 또는 거부합니다.")
이전에 리뷰남긴 승인, 거절의 메소드를 구분한다면 자연스럽게 API가 분리되게 되겠네요
무엇이 좋을지 생각해봐요!

2023-12-06 16:44 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/salary/domain/entity/constant/SalaryStatus.java
사소한 문제이지만 이 SalaryStatus를 Salary에서 사용하지 않는데, 오직 관리자 페이지를 위한 것이다보니 Admin아래로 가는게 더 좋지 않을까요?

2023-12-06 16:44 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/wish/application/usecase/WishInfoUseCase.java
WIshId를 삭제하고 UserId를 Wish의 pk로 즉, fk를 pk로 사용하는 방식에 대해서 생각해보고 연쇄적으로 수정될 수 있을 것 같아요!
Wish관련해서는요

2023-12-08 05:07 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/dto/CertificationInfo.java
넵 맞습니다! 변경하겠습니당~

2023-12-08 05:07 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/dto/res/CertificationDetailsResponse.java
> +        //인증 신청 날짜
대학원생이 인증을 신청한 날짜인데 Mentoring createdAt 이랑 어떤 연관이 있는지 이해가 잘 안갑니다..!!

2023-12-08 05:13 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/dto/res/MentoringResponse.java
1. 이름을 다른 dto (Domain)Response로 맞춘 상태인데 고민해보고 적절한 이름이 있다면 변경하겠습니다! 감사합니다

2.`MentoringResponse`를 보여주는 화면에 취소 및 환불 기능이 있길래 나중에 필요할 거 같아 `MentoringId`을 넣었습니다!

2023-12-08 05:21 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/dto/res/MentoringWithPaymentResponse.java
1. 어라... 추가하겠습니다. 감사합니다.

2. 후에 취소 또는 환불할 때 `payment`의 `deletedAt` 을 변경해야 한다고 생각해서 넣었습니다.!
<img width="461" alt="image" src="https://github.com/WE-ARE-RACCOONS/postgraduate-back/assets/110026001/1b0fefc8-aef2-415e-a7f0-ccf1082575d9">

3. `charge` 수수료 맞습니당

2023-12-08 05:21 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/dto/res/MentoringWithPaymentResponse.java
> +        String date,
`date`는 멘토링 진행 날짜이고 `salaryDoneDate`는 정산완료일 입니다

2023-12-08 05:24 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/dto/res/SeniorResponse.java
> +    private Status status;
`CertificationStatus` 어떨까요?

2023-12-08 05:28 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/dto/res/UserResponse.java
> +    private Long wishId;
음 그렇네요.. 좋은 지적 감사합니다. userId만 있는게 좋을 것 같아요 수정하겠습니다!

2023-12-08 05:32 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/dto/res/UserResponse.java
> +    private Role role;
넵 후배인 동시에 선배회원인지 확인하는 걸 `role`로 주고있는데 더 명확하게 `isSenior`변수로 Boolean 값을 주는 게 좋을까요?

2023-12-08 05:44 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/dto/res/SeniorResponse.java
> 인증 Status를 통해서 인증 여부와 인증 신청 정보 보는 것을 처리하는건가요?
맞습니다!

Status가 WAITING 이 아니라면 프론트에서 정보 보기를 비활성화 해야 한다고 생각했는데 혹시 백에서 어떤 처리가 필요한가요? 알려주시면 추가하겠습니다..!

2023-12-08 05:54 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/usecase/MentoringManageByAdminUseCase.java
> +        return mentorings.stream().map(AdminMapper::mapToMentoringResponse).toList();
넵 반영하겠습니다 감사합니다!

2023-12-08 05:57 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/usecase/MentoringManageByAdminUseCase.java
> +        if (!paymentGetService.existsByMentoring(mentoring)) {
오잉...그러게요 제가 왜 일을 두번했지..? 감사합니다

2023-12-08 06:03 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/usecase/SalaryManageByAdminUseCase.java
> +            if (getStatus(salaries) != DONE) {
1. SalaryUtils에 static 메소드로 두었습니다!

2. 어,, 이 로직이 아래 와프를 보고 만든 것입니다. `정산 완료`를 보여주는 기능이라 생각했는데 제가 잘못 이해한 걸까요.?
<img width="690" alt="image" src="https://github.com/WE-ARE-RACCOONS/postgraduate-back/assets/110026001/f9abdaa3-18bf-4cca-b2a7-a31b7e26d8f0">

2023-12-08 06:06 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/usecase/SeniorManageByAdminUseCase.java
>      public void updateSeniorStatus(Long seniorId, SeniorStatusRequest request) {
우왓 그렇네요 감사합니닷 ㅋㅋ ㅜㅜ

2023-12-08 06:12 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/mentoring/application/dto/res/AppliedMentoringDetailResponse.java
어라라 와프엔 있었는데 디자인엔 .. 없네요 .. 없애고 record 로 변경하겠습니다.

2023-12-08 06:14 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/presentation/AdminController.java
> +    private final WishInfoUseCase wishInfoUseCase;
오 좋습니다!!

2023-12-08 06:15 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
넵!

2023-12-08 06:27 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/salary/domain/entity/Salary.java
> +    private LocalDateTime salaryDoneDate;
넵 맞습니다,,

2023-12-08 06:28 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/salary/util/SalaryUtil.java
앗 감사합니다 ㅎㅎ 수정하겠습니다!

2023-12-08 06:28 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/wish/application/usecase/WishInfoUseCase.java
넵 !! 좋습니다

2023-12-08 07:12 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
> +    public static UserResponse mapToUserResponse(User user, Optional<Wish> wish) {
앗 이 부분이 [선배가 아닌 후배]만 나오는 게 아니고 그냥 [후배 전부] 나오는 거라 wish 가 없더라도 `UserResponse`를 만들어야 합니다..! 

그래서 Optional<Wish>로 받지 않고 아래 말씀해주신 것처럼 `seniorMyPageUseCase` 참고해 wish가 없는 mapper 따로 생성 후 `null`을 넣어주는 방식으로 변경하겠습니다!

2023-12-09 03:53 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/dto/res/MentoringWithPaymentResponse.java
> +        String date,
아하 `salaryDoneDate`는 정산 완료 시점에 `LocalDateTime.now()`로 저장하는데 멘토링 진행날짜는 아직 어떻게 변경될지 잘 모르겠어서 그대로 두었습니다.!

2023-12-09 04:02 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/usecase/SalaryManageByAdminUseCase.java
> +            if (getStatus(salaries) != DONE) {
지금 생각났는데 이 부분 `정산완료` 부분이라 합니다 ㅎㅎ 영수증 st 로 생각하심 된다네용

2023-12-09 10:26 UTC, ay-eonii commented
@ywj9811 수정사항입니다~!

1. 응답코드 재정의
2. 인증 신청 날짜: `senior.createdAt`
3. Record 로 변경 - 추가적으로 Mapper 변경
4. List 대신 하나의 dto 로 묶어서 반환
5. dummyAccount 대신 새로운 mapper로 null 생성
6. findAll() 호출하는 메서드 `getAll()`이 아닌 `all()` 로 통일
7. usecase 단 `@Transactinal`
8. 후배 정보 목록을 Wish로 불러오도록 로직을 변경했습니다. `wishId`를 그대로 dto에 포함합니다.

2023-12-09 13:17 UTC, ywj9811 requested changes
이외에 리뷰는 다 적용된건가요?

2023-12-09 13:17 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/admin/application/dto/UserInfo.java
>          Long wishId,
userId와 wishId가 같은 User꺼라면 wishId는 필요하지 않을 것 같기도 한데 없어도 될까요?

2023-12-09 13:23 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/dto/UserInfo.java
>          Long wishId,
음 저는 어차피 wish 에서 찾아오는 거라면 wishId를 두고 후에 wish/{wishId}에서 wish 가져올 때 User로 찾지 않고 wishId로 바로 찾는 게 더 좋지 않을까 하는데 ...  userId만 두는 게 낫나요?

2023-12-09 13:44 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/admin/application/dto/UserInfo.java
>          Long wishId,
우선은 이대로 진행해도 좋을 것 같아요
다만 나중에 wishId 자체를 삭제하고 userId를 pk로 가져가는 것 또한 생각해볼 수 있을 것 같아요!

2023-12-09 13:46 UTC, ywj9811 approved these changes
나머지 리뷰 사항만 다 됐다면 그대로 머지해도 괜찮을 것 같아요!

2023-12-09 13:46 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/admin/application/dto/UserInfo.java
>          Long wishId,
우선은 이대로 진행해도 좋을 것 같아요
다만 나중에 wishId 자체를 삭제하고 userId를 pk로 가져가는 것 또한 생각해볼 수 있을 것 같아요!

2023-12-09 14:27 UTC, merged