RAC-187 fix: 유효성 검사
WE-ARE-RACCOONS/postgraduate-back pull request #65
Opened 2023-12-10 14:05 UTC by ay-eonii

## 🦝 PR 요약
+ 유효성 검사 및 전반 점검

## ✨ PR 상세 내용
+ Request DTO에 대해 유효성 검사를 진행합니다.
+ 토큰이 필요한 API에 설명을 추가합니다.
+ DTO를 Record 를 사용하도록 변경합니다.
+ 관리자의 응답코드를 분리합니다.

## 🚨 주의 사항

## ✅ 체크 리스트

- [x] 리뷰어 설정했나요?
- [x] Label 설정했나요?
- [x] 제목 양식 맞췄나요? (ex. RAC-1 feat: 기능 추가)
- [x] 변경 사항에 대한 테스트 진행했나요?

2023-12-10 17:03 UTC, ywj9811 requested changes
언급한 두가지만 확인해주세요!
@Valid 동작 여부 제대로 확인 되었다면 위의 두가지만 확인 후 머지하면 좋을 것 같아요!

2023-12-11 04:43 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/auth/application/dto/req/SignUpRequest.java
> +        String major,
유저가 회원가입할 때 `major`와 `field`는 선택사항이라 붙이지 않았습니다

2023-12-11 04:44 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
놓쳤습니닷ㅎ 감사합니다 수정하겠습니다

2023-12-11 14:08 UTC, ywj9811 approved these changes

2023-12-11 14:08 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
넵 다 확인했습니다!

2023-12-11 14:15 UTC, merged