RAC-222 fix: 데이터 타입 변경
WE-ARE-RACCOONS/postgraduate-back pull request #67
Opened 2023-12-12 12:51 UTC by ay-eonii

## 🦝 PR 요약
+ 데이터 타입을 변경했습니다.

## ✨ PR 상세 내용
+ topic, question : 500자
+ info, target: 1000자
+ certification: 1000자

## 🚨 주의 사항
+ db에 반영해야 합니다

## ✅ 체크 리스트

- [x] 리뷰어 설정했나요?
- [x] Label 설정했나요?
- [x] 제목 양식 맞췄나요? (ex. RAC-1 feat: 기능 추가)
- [x] 변경 사항에 대한 테스트 진행했나요?

2023-12-12 13:11 UTC, ywj9811 requested changes
중간에 말한 것과 같이 1000, 500 이렇게 딱 맞춰버리면 \n과 같은 개행문제 영향때문에 글자수 유효성 체크는 프론트에서 우선 마치고 DB에는 TEXT로 그냥 해버리는건 어떨까요?

image가 profile도 있어서 그 부분도 추가해주세요!
그리고 chatLink 또한 255자로 충분한지 정확히 모르겠어서 TEXT로 하는게 안전하지 않을까? 생각도 들어요!

나머지 부분은 추가적으로 확인되면 그때 수정하도록 할게요!

2023-12-12 13:11 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
`@Column(~~, columnDefinition = "TEXT")`
그냥 이렇게 하는건 어떨까요?
줄바꿈을 하거나 그러면 \n 같은 개행문자가 추가된다는데 그러면 500으로 제한하면 실제 500자를 작성했을 때 오버될 수 있을 것 같아요

2023-12-15 13:45 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
넵 `TEXT` 로 변경하겠습니다!

2023-12-16 15:22 UTC, ywj9811 reviewed
image가 profile도 있어서 그 부분도 추가해주세요!
그리고 chatLink 또한 255자로 충분한지 정확히 모르겠어서 TEXT로 하는게 안전하지 않을까? 생각도 들어요!

이것만 추가해서 해주세요!

2023-12-17 14:04 UTC, ywj9811 approved these changes
머지해도 될 것 같아요!

2023-12-17 15:54 UTC, merged