RAC-249 feat: 매칭 기능
WE-ARE-RACCOONS/postgraduate-back pull request #80
Opened 2023-12-25 09:19 UTC by ay-eonii

## 🦝 PR 요약
+ 매칭 지원 기능을 구현했습니다.

## ✨ PR 상세 내용
+ `Wish` 엔티티에 매칭 지원 상태와 관련한 필드를 추가했습니다. (`status`)
+ 매칭 지원 완료하는 API를 구현했습니다.

## 🚨 주의 사항
관리자의 [후배회원] - [매칭지원완료] 칼럼은 
  + 빈칸
  + 대기중
  + 완료됨

으로 세 가지 입니다. `wish.status` 를 nullable 로 유지한 대신, '빈칸'의 경우 `wish.matchingReceive` 를 고려해 동의하지 않았다면 null 을 반환합니다. 혹시 더 나은 방법이 있다면 의견 주시면 감사하겠습니다 !

## ✅ 체크 리스트

- [x] 리뷰어 설정했나요?
- [x] Label 설정했나요?
- [x] 제목 양식 맞췄나요? (ex. RAC-1 feat: 기능 추가)
- [x] 변경 사항에 대한 테스트 진행했나요?

2023-12-25 14:30 UTC, ywj9811 requested changes
한번 확인 부탁드립니다!

2023-12-25 14:30 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
`Boolean wishStatus = wish.getMatchingReceive() ? wish.getStatus() : null;`
여기서 wishStatus에 null을 넣어주고 있는데, 
```java
public record UserInfo(
        @NotNull
        Long userId,
        @NotNull
        String nickName,
        @NotNull
        String phoneNumber,
        @NotNull
        LocalDateTime createdAt,
        @NotNull
        Boolean marketingReceive,
        @NotNull
        Boolean matchingReceive,
        @NotNull
        Long wishId,
        @NotNull
        Boolean wishStatus,
        @NotNull
        Boolean isSenior
) { }
```
이 코드의 wishStatus에 `@NotNull` 이 들어가면 이상하지 않을까요?
만약 테스트에서 아무런 오류가 없더라도 `@NotNull` 의 의미가 맞는지 싶어서요

2023-12-25 14:30 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
아니면 이 status에 대한 enum을 사용해서 3가지 상태를 모두 사용하는건 어떨까요?
회원가입할 때 wish에 대한 값을 경우에 따라 대기 혹은 거절 이렇게 넣어주는 방식은 어떻게 생각하나요?
현재는 회원가입시에 status가 기본적으로 false가 들어가다 보니 거절해도 대기중과 같은 컬럼이라 아예 나누는 방식을 제시해볼게욤

2023-12-25 15:45 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
> 이 코드의 wishStatus에 @NotNull 이 들어가면 이상하지 않을까요?

엇 그렇네요! 감사합니다

enum 사용하는 게 좋을 것 같아요!

2023-12-25 19:41 UTC, ywj9811 reviewed
제가 놓친걸 수 있긴한데 혹시 wishUpdate부분에서 status를 수정하는곳도 바뀐건가요?

2023-12-27 17:01 UTC, ywj9811 approved these changes
넵 확인했습니다~ 머지해주시면 될 것 같아요

2023-12-28 12:50 UTC, merged