RAC-251 fix: 전체점검
WE-ARE-RACCOONS/postgraduate-back pull request #84
Opened 2023-12-30 08:58 UTC by ay-eonii

## 🦝 PR 요약
+ 전체 점검 진행했습니다.
+ 충돌을 방지하기 위해 작업한 내용 먼저 머지 후, 노션에 점검사항 확인하면서 다른 브랜치에서 나머지 작업 하겠습니다.

## ✨ PR 상세 내용
+ 관리자에서 매칭 지원 정보를 기입하지 않은 [정보보기]가 아닌 [빈칸의 모달]을 보여주므로 지원 정보가 없다면 `null`을 반환하도록 했습니다.
+ 관리자에서 후배 멘토링 조회 시 선배 정보가 나오지 않는 오류를 해결했습니다.
+ 멘토링 취소 및 환불 기능을 추가했습니다. (환불의 경우 Payment 까지만)
+ 선배 상세 조회 시 로그인이 필요하므로 security에 권한 검사하도록 했습니다.
+ 멘토링 결제에서 멘토링 시간이 필요해 추가했습니다.

## 🚨 주의 사항

## ✅ 체크 리스트

- [x] 리뷰어 설정했나요?
- [x] Label 설정했나요?
- [x] 제목 양식 맞췄나요? (ex. RAC-1 feat: 기능 추가)
- [x] 변경 사항에 대한 테스트 진행했나요?

2023-12-30 09:47 UTC, ywj9811 requested changes
코멘트 한번씩 확인해주세요
그리고
`멘토링 취소 및 환불 기능을 추가했습니다. (환불의 경우 Payment 까지만)`
이 부분 제가 정확히 이해를 못해서 그런데 한번만 설명해주실 수 있을까요?

2023-12-30 09:47 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/admin/application/usecase/UserManageByAdminUseCase.java
```java
if (!wish.getMatchingReceive()) {
     throw new MatchingNotReceiveException();
}
```
여기서 굳이 안하고 조회할 때 애초에 MatchingReceive가 TRUE인 것만 조회하면 되지 않을까요?

```java
if (wish.getMajor() == null && wish.getField() == null) {
    throw new WishEmptyException();
}
```
그리고 여기서 만약 TRUE이지만 값들을 넣어놓지 않았다면 exception을 발생시키는게 맞을까요?
그냥 빈값을 보여주는게 맞지 않을까요?

2023-12-30 09:47 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
- `major == null && field == null` 이면 wishId 반환 안함
이게 꼭 필요할까요?
동의가 TRUE라면 그래도 보여주지만 빈값이라는 것만 알면 되지 않을까요?

2023-12-30 09:47 UTC, ywj9811 commented on src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
이부분은 알지만 우선 개발할 때 여러모로 귀찮을 것 같아서 나중에 도입하려 했던건데 추후에 한번에 잡는건 어떨까요?

2023-12-30 09:47 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
> +    @Operation(summary = "대학원생 상세 조회 | 토큰 필요")
근데 대학원생 상세 조회도 비회원이 들어가서 못보는건가요?

2023-12-30 10:32 UTC, ay-eonii reviewed
리뷰 감사합니닷 답글 확인 부탁드려용 ☺️

2023-12-30 10:32 UTC, ay-eonii commented on src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
넵 다른 부분은 토큰이 없다면 에외처리 되는데 
이 부분은 토큰에서 유저 정보 없이 인증만 필요했던 거라 이 부분만 먼저 추가했습니당

2023-12-30 10:32 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
> +    @Operation(summary = "대학원생 상세 조회 | 토큰 필요")
넵 와프에서

> 선배 프로필 열람은 로그인 후 가능합니다

라고 나와있더라구용

2023-12-30 10:32 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
그 방법도 좋은데
1. 빈값이라는 것을 알려주려면 새로운 필드가 하나 더 필요
2. 빈값이라면 상세조회가 없어서 wishId 필요없음

라고 생각했습니닷.

2023-12-30 10:32 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/usecase/UserManageByAdminUseCase.java
목록 말씀이신가용? 상세조회 말씀이신가요? 일단 와프에서는 `MatchingReceive`의 동의여부와는 상관없이 major 와 field 를 기입하지 않은 것에 한해 조회를 제한한 것 같습니다. 그래서 조회와는 상관없이 상태변경에 체크해야 할 사항인 것 같아 예외처리 했습니닷

2023-12-30 10:32 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/usecase/UserManageByAdminUseCase.java
애초에 지원 정보가 없다면 조회가 불가능하도록 한 게 기획 의도 같아서 (매칭지원정보 보기가 없으니) 조회 자체를 못하게 하는 게 맞다고 생각했습니다.

2023-12-30 14:19 UTC, ay-eonii commented
> 코멘트 한번씩 확인해주세요 그리고 `멘토링 취소 및 환불 기능을 추가했습니다. (환불의 경우 Payment 까지만)` 이 부분 제가 정확히 이해를 못해서 그런데 한번만 설명해주실 수 있을까요?

payple 없이 DB의 payment만 업데이트 하도록 구현했다는 말입니닷ㅎㅎ

2023-12-30 14:36 UTC, ywj9811 commented
> > 코멘트 한번씩 확인해주세요 그리고 `멘토링 취소 및 환불 기능을 추가했습니다. (환불의 경우 Payment 까지만)` 이 부분 제가 정확히 이해를 못해서 그런데 한번만 설명해주실 수 있을까요?
> 
> payple 없이 DB의 payment만 업데이트 하도록 구현했다는 말입니닷ㅎㅎ

아하 그렇다면 이 부분은 //todo 로 남겨주세요!

2023-12-30 14:37 UTC, ywj9811 requested changes
다시 한번만 봐주세요!

2023-12-30 14:37 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/admin/application/usecase/UserManageByAdminUseCase.java
와프에서 그렇게 하라는 말이 따로 보이지는 않는데 혹시 써져 있었나요? 빈칸의 모달이 그것을 의미하는건가요?
그게 아니라면
<img width="850" alt="image" src="https://github.com/WE-ARE-RACCOONS/postgraduate-back/assets/97458548/6f00da44-efa5-4284-8514-737f67d10d63">
이렇게 매칭 지원 동의는 O로 나오게 되는데, 계속해서 대기중에 상태 변경도 안되고 상세 보기도 안되게 될텐데, 이건 오히려 빈칸 보면 처리 완료로 변경하던 관리자 마음대로 하는게 좋지 않을까요?

그리고 `getWish()` `updateWishStatus()` 모두 동의하지 않으면 못본다고 생각해서 애초에 조회할 때 TRUE만을 조회하고 조회에 안나오면 `.orElseThrow()` 로 예외 처리하는게 좋지 않을까요?

의견 궁금합니다!

2023-12-30 14:37 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
> +    @Operation(summary = "대학원생 상세 조회 | 토큰 필요")
아하!

2023-12-30 14:37 UTC, ywj9811 commented on src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
security의 나머지 인증 부분은 마지막에 한번에 잡도록 합시다!
테스트할때 좀 귀찮아서ㅋㅋㅋ

2023-12-30 14:37 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
이 부분은 아래에 제가 달은 코멘트랑 의미가 같은 것 같아요!

2023-12-31 02:02 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/usecase/UserManageByAdminUseCase.java
아하... `빈칸의 모달`을 제가 잘 못 이해한 것 같네요ㅜㅜ ! 상세 조회에서 기입되지 않은 부분을 빈칸이라고 표현하신 게 맞는 것 같아요 이 부분은 다시 수정 후 리뷰 요청드리겠습니닷!!

`updateWishStatus()` 는 동의하지 않으면 예외 처리하는 게 맞는데, `getWish()`에 대해서는 매칭이 아닌 조회도 불가능하다는 말이 없는 것 같아서 기획에서 한 번 여쭤보고 진행하는 게 좋을 것 같습니다.


> 애초에 조회할 때 TRUE만을 조회

이 부분은 상세가 아닌 목록을 말씀하시는 게 맞나요? TRUE만을 조회하는 건 매칭동의에 O,X 두 가지가 있는데 TRUE만 조회하는 이유가 있을까요?

2023-12-31 04:47 UTC, ay-eonii commented on src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
ㅋㅋㅋㅋ그럼 이 부분은 테스트를 위해 제외하겠습니닷!

2023-12-31 14:44 UTC, ywj9811 requested changes
질문에 대해서 대답을 추가로 남겼어요! 확인 후 다시 리뷰요청 하면 보겠습니다~!

2023-12-31 14:44 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/admin/application/usecase/UserManageByAdminUseCase.java
상세 조회랑 업데이트 둘 다요!
O,X 둘 다 있지만 어쨌든 TRUE만 조회하는게 맞기도 하고 아래의 update에서도 TRUE가 아닌 경우를 예외처리하는 로직이 따로 있어서 차라리 조회 후 검사를 하는 것이 아닌 쿼리 자체를 그렇게 하는게 좋지 않을까 싶어서요

2023-12-31 14:44 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
아하... 빈칸의 모달을 제가 잘 못 이해한 것 같네요ㅜㅜ ! 상세 조회에서 기입되지 않은 부분을 빈칸이라고 표현하신 게 맞는 것 같아요 이 부분은 다시 수정 후 리뷰 요청드리겠습니닷!!

이 방법에 맞춰서 수정하면 좋을 것 같아요!

2024-01-02 03:41 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/usecase/UserManageByAdminUseCase.java
매칭 동의하지 않아도 상세조회는 가능하다고 기획 답변 받았습니다. 그럼 update 에서만 예외처리하면 될 것 같은데 어떤가요?

2024-01-02 04:02 UTC, ay-eonii commented
@ywj9811 
이전에 남겨주신 리뷰 반영해서 수정한 부분 아래에  정리했습니다~!

+ security의 인증 주석처리
+ 매칭 동의하지 않은 지원정보 상세조회 가능 
  + 기입하지 않은 부분 null 반환
+ 매칭 동의하지 않았거나 지원정보 기입하지 않으면 매칭지원완료 update 예외 발생

2024-01-02 12:49 UTC, ywj9811 commented
회의 결과로 나온 아예 조회를 하지 않는 방식으로 진행하면 좋을 것 같아요!
그렇게 TRUE만 조회하게 수정하면 될 것 같아요

2024-01-02 12:50 UTC, ywj9811 requested changes
회의 결과로 나온 아예 조회를 하지 않는 방식으로 진행하면 좋을 것 같아요!
그렇게 TRUE만 조회하게 수정하면 될 것 같아요

2024-01-02 16:39 UTC, ywj9811 requested changes
수정사항 한번만 확인해주세요

2024-01-02 16:39 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/admin/application/usecase/UserManageByAdminUseCase.java
```java
    public WishResponse getWish(Long wishId) {
        Wish wish = wishGetService.byWishId(wishId);
        if (!wish.getMatchingReceive()) {
            throw new MatchingNotReceiveException();
        }
        return AdminMapper.mapToWishResponse(wish);
    }

        if (!wish.getMatchingReceive()) {
            throw new MatchingNotReceiveException();
        }
        if (wish.getMajor() == null && wish.getField() == null) {
            throw new WishEmptyException();
        }
        wishUpdateService.updateWishStatus(wish);
    }
```
이 부분은
wishRepository에서 findByWishIdAndWish_MatchingReceiveIsTrue 이런식으로 조회해서
.orElseThrow로 MatchingNotReceiveException 를 발생시키는건 어떤지 물어본 거였어요

그리고
```java
if (wish.getMajor() == null && wish.getField() == null) {
       throw new WishEmptyException();
}
```
이 부분이 꼭 필요할까요?
물론 빈칸이 아닌 null이 들어있으면 예외를 잡는것이니 괜찮을 것 같기도해요!

2024-01-03 04:10 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/usecase/UserManageByAdminUseCase.java
이제야.. 이해했습니닷 ㅜㅜ

근데 MatchingNotReceiveException 예외를 발생시키면 존재하지 않는 wishId의 경우에도 미동의 예외가 발생합니닷
존재하지 않는 wish를 미동의로 표현하기 보다는,
미동의를 존재하지 않는 wish로 간주하여 WishNotFoundException 예외를 발생시킬까 하는데 어떠신가욤

2024-01-03 04:11 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/admin/application/usecase/UserManageByAdminUseCase.java
기입 정보가 없는데 매칭완료가 되는 게 이상하다 생각해서 저는 필요하다 생각합니닷ㅎㅅㅎ

2024-01-03 09:40 UTC, ywj9811 approved these changes
<img width="226" alt="image" src="https://github.com/WE-ARE-RACCOONS/postgraduate-back/assets/97458548/05a302e6-333d-46e4-a82e-445fb89d84d6">

이런식으로 사실 빈값이면 "", ""라서
```json
{
    "code": "ADM200",
    "message": "상세 조회에 성공하였습니다.",
    "data": {
        "nickName": "비버닉",
        "phoneNumber": "01080332443",
        "createAt": "2023-12-29T03:07:11.962781",
        "marketingReceive": true,
        "matchingReceive": true,
        "major": "",
        "field": ""
    }
}
```
null이 아닌 이렇게 ""로 나와서 저기서 걸러지지는 않아요
만약 진짜 DB에 Null로 들어가있다면 response를 생성하다가 npe가 발생할테니 저렇게 따로 예외 처리를 해줘도 문제가 될 것 같지는 않으니 그대로 진행해도 될 것 같아요

2024-01-03 10:46 UTC, merged