RAC-265 refactor : 성능 개선 작업
WE-ARE-RACCOONS/postgraduate-back pull request #85
Opened 2024-01-01 17:50 UTC by ywj9811

## 🦝 PR 요약
1차 성능 개선

## ✨ PR 상세 내용
성능 개선을 약간 진행해봤어요 물론 사실상 N+1 문제가 발생하는 부분을 찾아서 개선해보고 더 나아진다면 진행하였고,
N+1이 심하지 않았던 경우 오히려 성능이 악화되는 경우가 있어서 모두 변경하지는 않았습니다.
이러한 부분에 대해서는 더 알아보고 다시 진행해야 할 것 같습니다!

## 성능 개선 관련해서 (더미 데이터를 3000개~9000개 정도 넣어서 진행했습니다)
### 멘토링 관련
- 관리자 후배 멘토링 조회
1913ms -> 459ms
- 관리자 선배 멘토링 조회
2600ms -> 338ms
- 신청받은 멘토링 목록 조회
3000ms -> 244ms
- 신청받은 멘토링, 신청한 멘토링 상세 보기
성능차이가 안났지만, 메소드 이름이 마음에 안들어서 그냥 변경했습니다ㅎ
- 대학생 신청한 멘토링 관련
1901ms -> 471ms
### 대학원생 관련
- 대학원생 검색
마찬가지로 성능 크게 개선되지 않음
하지만, Page처리 로직에서 Deprecated되는 부분을 발견해서 Page관련 모두 수정했습니다
- 대학원생 필드 검색
n+1 해결했지만 개선은 딱히..
- 대학원생 상세 조회
이 또한 n=1 이었기 때문에 성능 개선은 기대하지 않았지만, 메소드가 맘에 안들어서 고쳤습니다. (너무 길어서)
- 관리자 대학원생 정보 목록 조회
191ms -> 103ms
이 경우는 service를 여러개 호출해서 기본적으로 발생하는 쿼리의 종류가 많아서 많은 개선을 하지 못했습니다
### 시간(Available) 관련
- 대학원생 가능 시간 조회
n+1 확인 후 개선하였으나
36ms -> 30ms
테스트를 여러번 하면 이정도는 그냥 왔다갔다 하면서 나올 수 있지 않을까...
개선이 되지는 않은 것 같습니다.
### 결제 관련
- 관리자 결제 목록 조회
이 경우는 n+1을 개선하니 오히려 성능이 안좋아졌다.
그래서 dto만 조회하면서 n+1을 방지하도록 수정해 보았는데, 여전히 더 안좋았다.
결국 다시 원복하였습니다.
### 정산 관련
- 관리자 페이지 정산 목록 조회
이 또한 service를 여러개 사용해서 다음 개선때 손을 볼 계획입니다.
- 대학원생 정산 목록 조회
3243ms -> 225ms
- 관리자 페이지 선배 정산 상세정보, 대학원생 정산 예정액, 다음 정산 예정일 보기 (같은 로직)
각각
2053ms -> 185ms
1999ms -> 170ms
### 매칭 희망 관련
- 관리자 후배 정보 목록
42ms -> 35ms
개선 여부를 정확히 모르겠지만 N+1 발생은 해결함

그 외에 개선하면서 생긴 변경점에 대한 테스트 코드 수정을 진행하였습니다

자세한 정보는 노션에 정리해두었습니다~

## 🚨 주의 사항
Payment에 왜 Status가 4개였을까요,,? 기억이 안나서...
그냥 DONE, CANCEL, PROBLEM 이렇게가 맞지 않을까요? (완료, 환불, 문제 발생)
그리고 `private Status status = Status.IMPOSSIBLE` 이걸로 되어있던 부분을 DONE이 Default가 되도록 수정했습니다
결제가 되었을 때 Payment가 생성될텐데, 그러면 결제 완료로 표시되야 하는게 아닐까? 싶어서요!
그리고 Payment에 paidAt이 있었는데, 결제일이 목적이라면 사실 createdAt이랑 동일하지 않을까? 싶어서 삭제했습니다
혹시 다른 목적이 있는 컬럼이었다면 다시 되살릴게요!

## ✅ 체크 리스트
- [x] 리뷰어 설정했나요?
- [x] Label 설정했나요?
- [x] 제목 양식 맞췄나요? (ex. RAC-1 feat: 기능 추가)
- [x] 변경 사항에 대한 테스트 진행했나요?

2024-01-02 06:01 UTC, ay-eonii requested changes
저도 결제 시 payment 가 생성되는 거라고 생각하고 있었는데 지금 생각해보니 이전에 멘토링 성사됐을 때 생기는 걸로 논의하여 상태에 `POSSIBLE`, `IMPOSSIBLE` 을 두었던 걸로 기억합니다.! 
> DONE, CANCEL, PROBLEM

이렇게 가는 게 맞는 것 같아용

2024-01-02 06:04 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorProfileRequest.java
> +        }
이것도 `@NotEmpty` 사용할 수 있을 것 같아용 ! 단순 의견이어서 편하신 걸로 선택하심 될 듯해용

2024-01-02 11:09 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryDslRepository.java
> +    List<Salary> findAllBySeniorIdAndStatus(Senior senior, Boolean status);
확인했습니다!

2024-01-02 11:09 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorMyPageProfileRequest.java
> +        }
좋은 것 같아요!

2024-01-02 12:48 UTC, ywj9811 commented
`@NotEmpty` 가 아닌 수동으로 처리하면 예외를 구체적으로 처리할 수 있어서 그대로 사용하면 어떨까 싶어요!

2024-01-03 08:50 UTC, ay-eonii approved these changes
확인했습니다!

2024-01-03 18:37 UTC, ywj9811 commented
추가한 action 동작 여부 확인하려고 재오픈 했습니다!

2024-01-03 18:39 UTC, merged