RAC-254 test: 통합테스트
WE-ARE-RACCOONS/postgraduate-back pull request #91
Opened 2024-01-10 08:47 UTC by ay-eonii

## 🦝 PR 요약
+ 통합테스트 코드 작성

## ✨ PR 상세 내용
+ 멘토링 관련 테스트 코드를 작성했습니다.
+ 인증 관련 테스트 코드를 작성했습니다.
+ 응답의 주요 데이터 위주로 테스트를 진행했습니다.

## 🚨 주의 사항
+ senior, user 관련 테스트는 나누어서 진행하겠습니다.

## ✅ 체크 리스트

- [x] 리뷰어 설정했나요?
- [x] Label 설정했나요?
- [x] 제목 양식 맞췄나요? (ex. RAC-1 feat: 기능 추가)
- [x] 변경 사항에 대한 테스트 진행했나요?

2024-01-10 16:22 UTC, ywj9811 requested changes
정말 작은 몇가지 부분만 수정하면 정말 좋을 것 같아요!
노션에 정리해준 내용이랑 같이 참고하니 리뷰하기도 훨씬 수월하고 좋네요 ㅎㅎ

2024-01-10 16:22 UTC, ywj9811 commented on src/test/java/com/postgraduate/domain/mentoring/presentation/MentoringControllerTest.java
> +    @EnumSource(value = Status.class, names = {"WAITING", "DONE"})
이거 아주 좋아요 몰랐던 내용이라서ㅋㅋ
고맙슴다

2024-01-10 16:22 UTC, ywj9811 commented on src/test/java/com/postgraduate/domain/mentoring/presentation/MentoringControllerTest.java
공부를 엄청 많이 하고 했네요! 잘못했다고 한 부분도 다시 잡혀있고요ㅎㅎ

`.andExpect(jsonPath("$.data.mentoringInfos[0].nickName").value("선배"))`
아래에는 대부분이 생성한 인스턴스에서 값을 가져와서 사용하는데, 몇 부분이 하드코딩을 해놓은 모습이 있어요!

그리고 응답코드나, 응답메시지도 하드 코딩이 아닌 그대로 값을 가져와서 사용하면 나중에 응답 코드 혹은 메시지가 수정되어도 그대로 테스트가 통과될 수 있지 않을까요?

되게 깔끔하게 잘 작성해서 좋네요! 추가로 예외가 발생하는 경우가 많이 존재할텐데 그에 대한 테스트도 같이 추가된다면 더욱 좋을 것 같아요!

2024-01-10 16:22 UTC, ywj9811 commented on src/test/java/com/postgraduate/domain/auth/presentation/AuthControllerTest.java
제가 Mentoring부터 확인해서 이 부분에도 마찬가지로 이야기를 할 수 있을 것 같아요
마찬가지로 응답 코드 그리고 메시지를 하드코딩이 아닌 저장되어 있는 값을 가져다가 사용하면 수정을 해야하는 요인이 줄어들 수 있지 않을까요?

그리고 여기서는 Mockito를 사용하고 다른 테스트에서는 BDDMockito를 사용하고 있는데 이 부분은 사소하고 사소한 부분이라 상관은 없을 것 같아요ㅋㅋ

모르던 부분도 있어서 새롭게 많이 배워서 좋네요!

2024-01-11 04:50 UTC, ay-eonii commented on src/test/java/com/postgraduate/domain/mentoring/presentation/MentoringControllerTest.java
> 그리고 응답코드나, 응답메시지도 하드 코딩이 아닌 그대로 값을 가져와서 사용하면 나중에 응답 코드 혹은 메시지가 수정되어도 그대로 테스트가 통과될 수 있지 않을까요?

오 좋아요!! 감사합니다 :)

예외에 대한 부분도 추가해보도록 할게욧!

2024-01-11 04:51 UTC, ay-eonii commented on src/test/java/com/postgraduate/domain/auth/presentation/AuthControllerTest.java
넵 ㅎㅎ ! 감사합니다

2024-01-11 04:51 UTC, ay-eonii commented on src/test/java/com/postgraduate/domain/mentoring/presentation/MentoringControllerTest.java
> +    @EnumSource(value = Status.class, names = {"WAITING", "DONE"})
헤헤 기쁘네요

2024-01-11 06:37 UTC, ay-eonii commented
@ywj9811 

수정 내용입니다~! 
+ 응답 관련 enum 사용
+ 예외 테스트 추가
  + 멘토링 상태변경, 멘토링 신청 시 날짜, 권한 변경
+ 선배로 변경 시 선배 가입 여부 확인하도록 수정
  + `JwtUseCase.seniorToken()`와 `JwtUseCase.changeSenior()` 에서 중복으로 `checkDelete()` 검사를 하고 있어 `changeSenior()`에서 선배로 가입한 유저인지 확인하도록 변경했습니다.

2024-01-13 14:11 UTC, ywj9811 approved these changes
확인했습니다!
이후에 필요한 부분이 생기면 추가하면서 진행하도록 하죠!

2024-01-13 14:54 UTC, merged