RAC-254 test: 통합테스트
WE-ARE-RACCOONS/postgraduate-back pull request #93
Opened 2024-01-14 05:03 UTC by ay-eonii

## 🦝 PR 요약
+ user, senior, salary 통합테스트를 진행했습니다.

## ✨ PR 상세 내용
+ 각 정상테스트, 예외테스트를 진행했습니다.
+ 올바르지 않은 요일로 요청했을 때 예외를 정의했습니다. (`DayAvailableException`)

## 🚨 주의 사항

## ✅ 체크 리스트

- [x] 리뷰어 설정했나요?
- [x] Label 설정했나요?
- [x] 제목 양식 맞췄나요? (ex. RAC-1 feat: 기능 추가)
- [x] 변경 사항에 대한 테스트 진행했나요?

2024-01-16 14:39 UTC, ywj9811 requested changes
테스트 코드는 문제 없어 보이지만 예외가 발생할 수 있는 경우가 정말 많이 존재하는데 케이스를 더 추가해보는건 어떨까요?
Dto에서 발생하는 예외도 있고 유스케이스 혹은 서비스를 살펴보면 발생해서 올라오는 예외들도 많아요

혹은 이렇게 진행하고 앞으로 어떤 방식으로 진행하면서 추가될 예정이라면 원하는 방식을 이야기 해보고 진행해도 괜찮을 것 같아요

2024-01-16 14:39 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/available/application/util/AvailableUtil.java
고쳐야지 하고 놓치고 있었던 부분이었는데 좋네요

2024-01-16 14:39 UTC, ywj9811 commented on src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
이 부분은 환불 로직 추가하면서 다시 잡아보도록 할게요! 가능하면 //Todo로 표시만 해주실 수 있나요?

2024-01-17 02:49 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
넵 !

2024-01-17 02:49 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/available/application/util/AvailableUtil.java
감사합니다 🙇‍♀️

2024-01-17 02:55 UTC, ay-eonii commented
예외에 대해 좀 더 꼼꼼하게 테스트 작성 해보겠습니다 ! 
ResponseMessage의 예외메시지를 위주로 작성했는데, response의 data 부분도 테스트를 진행하는 게 좋을까요?

2024-01-17 07:03 UTC, ywj9811 commented
> @ywj9811 예외에 대해 좀 더 꼼꼼하게 테스트 작성 해보겠습니다 ! ResponseMessage의 예외메시지를 위주로 작성했는데, response의 data 부분도 테스트를 진행하는 게 좋을까요?

음 data부분에 대한 테스트까지 작성하는 것이 무리라면 괜찮기는 할 것 같아요
다만 요청이 오는 경우에 따라서 useCase ~ service에서 발생하는 예외에 대해서는 더 다양하게 체크할 수 있으면 좋을 것 같아요!
추가로 @Valid에 대한 테스트도 가능할까요?

2024-01-21 13:26 UTC, ywj9811 approved these changes
확인했어요 테스트 코드는 계속해서 더 작성할걸 찾거나 생기면 작성해도 될것 같아요

2024-01-21 13:42 UTC, ay-eonii commented on src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorMyPageResponse.java
저번에 socialId 추가해달라길래 했었는데 다른브랜치에서 먼저 반영해주셔서 ㅎㅎ 이렇게 됐어욤

2024-01-21 13:42 UTC, merged